language: java
sudo: false

before_script:
 - export VERSION=$(cat gradle.properties | sed -n '/version =/p' | cut -d '=' -f2 | cut -d ' ' -f2)
script:
 - ./gradlew build bootJar
after_success:
 - bash <(curl -s https://codecov.io/bash)
deploy:
 provider: releases
 api_key: $GITHUB_TOKEN
 file_glob: true
 file: "build/libs/retipy-rest-${VERSION}.jar"
 skip_cleanup: true
 overwrite: true
 on:
  repo: alevalv/retipy-rest
   branch: master
   tags: true
